---
  - hosts: all
    tasks:
      - name: Install the gpg key for nodejs LTS
        become: true
        apt_key:
          url: "http://deb.nodesource.com/gpgkey/nodesource.gpg.key"
          validate_certs: no
      - name: Install the nodejs LTS repo
        become: true
        apt_repository:
          repo: "deb http://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
          state: present
          update_cache: yes
      - name: Install NodeJS
        become: true
        apt:
          name: nodejs
          state: present
      - name: Install PM2
        become: true
        command: npm install -g pm2
      - name: Create PM2 service
        become: true
        command: sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
      - name: PM2 Startup configuration
        command: pm2 start /home/ubuntu/buildreader/server.js --name="buildreader"
        args:
          chdir: /home/ubuntu/buildreader/
      - name: PM2 startup configuration save
        command: pm2 save
